a=int(input("Enter the value of first number: "))
b=int(input("Enter the value of second number: "))
print(("Addition:",a+b))
print(("Subtraction:",a-b))
print(("Multiplication:",a*b))
print(("Division:",a/b))